return {
  "nvim-treesitter/nvim-treesitter",
  event = { "User LazyFile", "VeryLazy" },
  lazy = vim.fn.argc(-1) == 0,
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "diff",
      "html",
      "http",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
    },
    sync_install = false,
    auto_install = true,
    ignore_install = { "javascript" },
  },
  config = function(_, opts)
    require("nvim-treesitter.configs").setup(opts)
  end,
}
